name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 5.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  nb_utils: ^4.6.10
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  cached_network_image: ^3.2.1
  google_fonts: ^2.3.3
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  url_launcher: ^6.1.2
  flutter_vector_icons: ^1.0.0

  #Firebase
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  firebase_remote_config: ^2.0.9
  firebase_auth: ^3.3.18
  firebase_storage: ^10.2.16
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^3.1.15

  flutter_staggered_grid_view: ^0.6.1
  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.0.4
  dotted_border: 2.0.0+2
  flutter_remix: ^0.0.3
  flutter_rating_bar: ^4.0.1
  date_time_picker: 2.1.0

  #image:
  path_provider: ^2.0.10
  image_picker: ^0.8.5+3
  multi_image_picker: ^4.8.1
  photo_view: ^0.13.0
  file_picker: ^4.5.1
  lottie: ^1.3.0

  # PAYMENTS
  flutter_stripe: ^3.0.0
  razorpay_flutter: ^1.3.0
  flutterwave_standard: 1.0.3

  #notifications:
  onesignal_flutter: ^3.3.0

  #chart
  syncfusion_flutter_charts: ^20.1.56
  charts_flutter: ^0.12.0

  #map:
  geocoding: ^2.0.4

  flutter_html: ^3.0.0-alpha.3

  flutter_image_stack: ^0.0.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

